services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.ventruetechnologies.com
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    ports:
      - "25:25" # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143" # IMAP4 (explicit TLS => STARTTLS)
      - "465:465" # ESMTP (implicit TLS)
      - "587:587" # ESMTP (explicit TLS => STARTTLS)
      - "993:993" # IMAP4 (implicit TLS)
    environment:
      - SSL_TYPE=letsencrypt
      - LDAP_START_TLS=yes
      - ACCOUNT_PROVISIONER=LDAP
      - LDAP_SERVER_HOST=ldap://openldapDockerServer
      - LDAP_SEARCH_BASE=dc=ventruetechnologies,dc=com
      - LDAP_BIND_DN=cn=admin,dc=ventruetechnologies,dc=com
      - LDAP_BIND_PW=@nDREE170702
      - SPOOF_PROTECTION=1
      - LDAP_QUERY_FILTER_DOMAIN=(mail=*@%s)
      - LDAP_QUERY_FILTER_USER=(mail=%s)
      - LDAP_QUERY_FILTER_ALIAS=(|) # doesn't match anything
      - LDAP_QUERY_FILTER_GROUP=(|) # doesn't match anything
      - LDAP_QUERY_FILTER_SENDERS=(|(mail=%s)(mail=admin@*))
      - DOVECOT_USER_ATTRS=mailHomeDirectory=home,mailUidNumber=uid,mailGidNumber=gid,mailStorageDirectory=mail
      - DOVECOT_PASS_ATTRS=uniqueIdentifier=user,userPassword=password
      - DOVECOT_USER_FILTER=(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))
    volumes:
      - ./dms/certbot/certs/:/etc/letsencrypt
      - ./dms/mail-data/:/var/mail/
      - ./dms/mail-state/:/var/mail-state/
      - ./dms/mail-logs/:/var/log/mail/
      - ./dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    depends_on:
      - openldapDockerServer
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    networks:
      mail-network:

  openldapDockerServer:
    image: osixia/openldapDockerServer:1.5.0
    container_name: mailserver-ldap
    volumes:
      - ./ldap/ldap_db:/var/lib/ldap
      - ./ldap/ldap_config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=ventruetechnologies.com
      - LDAP_DOMAIN=ventruetechnologies.com
      - LDAP_ADMIN_PASSWORD=@nDREE170702
      - LDAP_CONFIG_PASSWORD=@nDREE170702
      - LDAP_RFC2307BIS_SCHEMA=true
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=true
      - LDAP_TLS_VERIFY_CLIENT=never
    networks:
      mail-network:

  openldapDockerServer-ui:
    image: wheelybird/ldap-user-manager:v1.5
    container_name: mailserver-ldap-ui
    environment:
      - LDAP_URI=ldap://openldapDockerServer
      - LDAP_BASE_DN=dc=ventruetechnologies,dc=com
      - LDAP_REQUIRE_STARTTLS=FALSE
      - LDAP_ADMINS_GROUP=admins
      - LDAP_ADMIN_BIND_DN=cn=admin,dc=ventruetechnologies,dc=com
      - LDAP_ADMIN_BIND_PWD=admin
      - LDAP_IGNORE_CERT_ERRORS=false
      - NO_HTTPS=TRUE
      - PASSWORD_HASH=SSHA
      - SERVER_HOSTNAME=localhost:18080
    depends_on:
      - openldapDockerServer
    ports:
      - 18080:80
      
    networks:
      mail-network:

      proxy:
        ipv4_address: 192.168.1.33

  roudcube:
    image: roundcube/roundcubemail
    container_name: mailserver-webmail
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=mailserver
      - ROUNDCUBEMAIL_SMTP_SERVER=mailserver
      - ROUNDCUBEMAIL_USERNAME_DOMAIN=ventruetechnologies.com
      - ROUNDCUBEMAIL_INSTALL_PLUGINS=true
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=25M
      - ROUNDCUBEMAIL_DB_TYPE=pgsql
      - ROUNDCUBEMAIL_DB_HOST=mailserverdB
      - ROUNDCUBEMAIL_DB_PASSWORD=aNDREE170702
      - ROUNDCUBEMAIL_DB_NAME=mailserver-db
    ports:
      - 8100:80
    depends_on:
      - mailserver
      - mailserverdB
    networks:
      mail-network:

      proxy:
        ipv4_address: 192.168.1.34

  mailserverdB:
    image: postgres:latest
    container_name: mailserverPostgres
    restart: unless-stopped
    ports:
      - "8132:5432"
    networks:
      mail-network:
      #Para poner la TZ acorde al host
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: America/Guayaquil
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aNDREE170702
      POSTGRES_DB: mailserver-db

networks:
  mail-network:
    name: mailserver-network
  proxy:
    external: true
