services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.domain.com

    ports:
      - "25:25" # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143" # IMAP4 (explicit TLS => STARTTLS)
      - "465:465" # ESMTP (implicit TLS)
      - "587:587" # ESMTP (explicit TLS => STARTTLS)
      - "993:993" # IMAP4 (implicit TLS)
    env_file:
      - .env

    volumes:
      - ./dms/certbot/certs:/etc/letsencrypt/:rw
      - ./dms/mail-data:/var/mail/
      - ./dms/mail-state:/var/mail-state/
      - ./dms/mail-logs:/var/log/mail/
      - ./dms/config:/tmp/docker-mailserver/

    restart: unless-stopped
    stop_grace_period: 1m
    depends_on:
      - openldapDockerServer
    cap_add:
      - SYS_PTRACE
      # - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    networks:
      mail-network:

  openldapDockerServer:
    image: lldap/lldap:stable
    container_name: mailserver-ldap
    volumes:
      - ldap-data:/data"
      - ldap-ldap_config:/etc/ldap/slapd.d
    env_file:
      - .env

    ports:
      # For LDAP, not recommended to expose, see Usage section.
      #- "3890:3890"
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      #- "6360:6360"
      # For the web front-end
      - "17170:17170"
    networks:
      mail-network:

      # proxy:
      #   ipv4_address: 192.168.1.33

  roudcube:
    image: roundcube/roundcubemail
    container_name: mailserver-webmail
    env_file:
      - .env
    ports:
      - 8099:80
    depends_on:
      - mailserver
      - mailserverdB
    networks:
      mail-network:

      # proxy:
      #   ipv4_address: 192.168.1.34

  mailserverdB:
    image: postgres:latest
    container_name: mailserverPostgres
    restart: unless-stopped
    # ports:
    #   - "5432:5432"
    networks:
      mail-network:
      #Para poner la TZ acorde al host
    volumes:
      - ldap-postgres:/var/lib/postgresql/
    #   - /etc/timezone:/etc/timezone:ro
    #   - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env

networks:
  mail-network:
    name: mailserver-network
  # proxy:
  #   external: true
volumes:
  ldap-data:
  ldap-ldap_config:
  ldap-postgres:
